"""add_rohlik_address_id

Revision ID: 190f5da7cfbf
Revises: b7d2e4a9c1f0
Create Date: 2026-07-05 14:06:29.496184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190f5da7cfbf'
down_revision: Union[str, None] = 'b7d2e4a9c1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rohlik_address_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rohlik_address_id')
    # ### end Alembic commands ###
