"""add_rohlik_image_url_to_list_item

Revision ID: 39f1d90d41bf
Revises: 94b50c4c2802
Create Date: 2026-06-02 18:25:24.100317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f1d90d41bf'
down_revision: Union[str, None] = '94b50c4c2802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('rohlik_image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list_items', 'rohlik_image_url')
    # ### end Alembic commands ###
